# Generated by Django 3.2.3 on 2021-06-05 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountChild', models.ManyToManyField(blank=True, to='app.AccountChild')),
                ('accountGroup', models.ManyToManyField(blank=True, to='app.AccountGroup')),
                ('deliveries', models.ManyToManyField(blank=True, to='app.Deliveries')),
                ('deliveriesDestination', models.ManyToManyField(blank=True, to='app.DeliveryDestinations')),
                ('deliveryPhotos', models.ManyToManyField(blank=True, to='app.DeliveryPhotos')),
                ('deliveryitemsGroup', models.ManyToManyField(blank=True, to='app.DeliveryItemsGroup')),
                ('deliveryitemsMerch', models.ManyToManyField(blank=True, to='app.DeliveryItemMerch')),
                ('driver', models.ManyToManyField(blank=True, to='app.Driver')),
                ('journal', models.ManyToManyField(blank=True, to='app.Journal')),
                ('journalEntries', models.ManyToManyField(blank=True, to='app.JournalEntries')),
                ('merchInventory', models.ManyToManyField(blank=True, to='app.MerchandiseInventory')),
                ('party', models.ManyToManyField(blank=True, to='app.Party')),
                ('poitemsMerch', models.ManyToManyField(blank=True, to='app.POItemsMerch')),
                ('purchaseOrder', models.ManyToManyField(blank=True, to='app.PurchaseOrder')),
                ('salesContract', models.ManyToManyField(blank=True, to='app.SalesContract')),
                ('scitemsMerch', models.ManyToManyField(blank=True, to='app.SCItemsMerch')),
                ('subGroup', models.ManyToManyField(blank=True, to='app.AccountSubGroup')),
                ('truck', models.ManyToManyField(blank=True, to='app.Truck')),
                ('warehouse', models.ManyToManyField(blank=True, to='app.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
        ),
    ]
