# Generated by Django 3.2.3 on 2021-06-05 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journalApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile-pictures/person.png', null=True, upload_to='profile-pictures/'),
        ),
    ]
