# Generated by Django 3.2.3 on 2021-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210605_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='accountChild',
        ),
        migrations.AddField(
            model_name='party',
            name='accountChild',
            field=models.ManyToManyField(related_name='party', to='app.AccountChild'),
        ),
    ]
