# Generated by Django 3.1.7 on 2021-06-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210609_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='scitemsMerch',
            field=models.ManyToManyField(blank=True, to='app.TempSCItemsMerch'),
        ),
    ]
