# Generated by Django 3.2.3 on 2021-06-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210609_1926'),
        ('app', '0009_auto_20210609_1931'),
    ]

    operations = [
    ]
