# Generated by Django 3.2.3 on 2021-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_0009_auto_20210609_1926_0009_auto_20210609_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tempSCOtherFees',
            field=models.ManyToManyField(blank=True, to='app.TempSCOtherFees'),
        ),
    ]
