# Generated by Django 3.2.3 on 2021-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_branch_tempscotherfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempscitemsmerch',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
