# Generated by Django 3.1.7 on 2021-06-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210610_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='datetimeApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
