# Generated by Django 3.2.3 on 2021-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210610_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='permanence',
            field=models.CharField(choices=[('Real', 'Real'), ('Nominal', 'Nominal')], max_length=50),
        ),
    ]
