# Generated by Django 3.1.7 on 2021-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210610_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubgroup',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='permanence',
            field=models.CharField(max_length=50),
        ),
    ]
