# Generated by Django 3.2.3 on 2021-06-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210615_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amountWithheld',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='atcCode',
        ),
        migrations.CreateModel(
            name='POatc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountWithheld', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poatccodes', to='app.atc')),
                ('purchaseOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poatccodes', to='app.purchaseorder')),
            ],
        ),
    ]
