# Generated by Django 3.2.3 on 2021-06-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210615_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poatc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poatc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='poatc',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poatc', to='app.purchaseorder'),
        ),
    ]
