# Generated by Django 3.2.3 on 2021-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210616_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='poatc',
            field=models.ManyToManyField(blank=True, to='app.POatc'),
        ),
    ]
