# Generated by Django 3.2.3 on 2021-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_branch_poatc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='taxPeso',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
