# Generated by Django 3.2.3 on 2021-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_purchaseorder_taxpeso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salescontract',
            old_name='amountWithheld',
            new_name='amountTotal',
        ),
        migrations.RemoveField(
            model_name='salescontract',
            name='atcCode',
        ),
        migrations.RemoveField(
            model_name='salescontract',
            name='salesOrder',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fullyPaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='fullyPaid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
