# Generated by Django 3.2.3 on 2021-06-19 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210617_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('dateRequested', models.DateField()),
                ('dateNeeded', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('intendedFor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
            },
        ),
        migrations.CreateModel(
            name='ReceivingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('dateReceived', models.DateField()),
                ('amountPaid', models.DecimalField(decimal_places=5, max_digits=18)),
                ('amountDue', models.DecimalField(decimal_places=5, max_digits=18)),
                ('amountTotal', models.DecimalField(decimal_places=5, max_digits=18)),
                ('taxType', models.CharField(blank=True, max_length=20, null=True)),
                ('taxRate', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('taxPeso', models.DecimalField(decimal_places=5, max_digits=20)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentPeriod', models.CharField(max_length=50)),
                ('chequeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('fullyPaid', models.BooleanField(default=False, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rrApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rrCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivingreport', to='app.journal')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivingreport', to='app.party')),
                ('purchaseOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivingreport', to='app.purchaseorder')),
            ],
            options={
                'verbose_name': 'Receiving Report',
                'verbose_name_plural': 'Receiving Reports',
            },
        ),
        migrations.RemoveField(
            model_name='poitemsmerch',
            name='inputVat',
        ),
        migrations.CreateModel(
            name='RRItemsMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('purchasingPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('totalPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('delivered', models.BooleanField(default=False, null=True)),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsmerch', to='app.merchandiseinventory')),
                ('receivingReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsmerch', to='app.receivingreport')),
            ],
            options={
                'verbose_name': 'RR Items Merch',
                'verbose_name_plural': 'RR Items Merchs',
            },
        ),
        migrations.CreateModel(
            name='RRatc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountWithheld', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rratc', to='app.atc')),
                ('receivingReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rratc', to='app.receivingreport')),
            ],
        ),
        migrations.CreateModel(
            name='PRItemsMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pritemsmerch', to='app.merchandiseinventory')),
                ('purchaseRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pritemsmerch', to='app.purchaserequest')),
            ],
            options={
                'verbose_name': 'PR Items Merch',
                'verbose_name_plural': 'PR Items Merchs',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaseRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseorder', to='app.purchaserequest'),
        ),
    ]
