# Generated by Django 3.2.3 on 2021-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210619_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pritemsMerch',
            field=models.ManyToManyField(blank=True, to='app.PRItemsMerch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='purchaseRequest',
            field=models.ManyToManyField(blank=True, to='app.PurchaseRequest'),
        ),
        migrations.AddField(
            model_name='branch',
            name='receivingReport',
            field=models.ManyToManyField(blank=True, to='app.ReceivingReport'),
        ),
        migrations.AddField(
            model_name='branch',
            name='rratc',
            field=models.ManyToManyField(blank=True, to='app.RRatc'),
        ),
        migrations.AddField(
            model_name='branch',
            name='rritemsMerch',
            field=models.ManyToManyField(blank=True, to='app.RRItemsMerch'),
        ),
    ]
