# Generated by Django 3.2.3 on 2021-06-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210619_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='journal',
        ),
    ]
