# Generated by Django 3.2.3 on 2021-06-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_vendorquotesitemsmerch_vendorquotesmerch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorquotesitemsmerch',
            name='vendorquotesmerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendorquotesitemsmerch', to='app.vendorquotesmerch'),
        ),
    ]
