# Generated by Django 3.2.3 on 2021-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_vendorquotesitemsmerch_vendorquotesmerch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='vendorQuotesItemsMerch',
            field=models.ManyToManyField(blank=True, to='app.VendorQuotesItemsMerch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vendorQuotesMerch',
            field=models.ManyToManyField(blank=True, to='app.VendorQuotesMerch'),
        ),
    ]
