# Generated by Django 3.2.3 on 2021-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210625_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SCOtherFees',
            new_name='TempSCOtherFees',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='SCOtherFees',
        ),
        migrations.AddField(
            model_name='branch',
            name='tempSCOtherFees',
            field=models.ManyToManyField(blank=True, to='app.TempSCOtherFees'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='salesContract',
            field=models.ManyToManyField(blank=True, to='app.TempSalesContract'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='scitemsMerch',
            field=models.ManyToManyField(blank=True, to='app.TempSCItemsMerch'),
        ),
    ]
