# Generated by Django 3.2.3 on 2021-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210625_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scitemsmerch',
            name='delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
