# Generated by Django 3.2.3 on 2021-06-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210625_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salescontract', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tempsalescontract', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='tempscotherfees',
            name='salesContract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scotherfees', to='app.salescontract'),
        ),
    ]
