# Generated by Django 3.2.3 on 2021-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210625_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='salesContract',
            field=models.ManyToManyField(blank=True, to='app.SalesContract'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='scitemsMerch',
            field=models.ManyToManyField(blank=True, to='app.SCItemsMerch'),
        ),
    ]
