# Generated by Django 3.2.3 on 2021-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210625_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='scatc',
            field=models.ManyToManyField(blank=True, to='app.SCatc'),
        ),
    ]
