# Generated by Django 3.2.3 on 2021-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_branch_scatc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempscotherfees',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
