# Generated by Django 3.2.3 on 2021-06-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_tempscotherfees_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('dateInward', models.DateField()),
                ('amountTotal', models.DecimalField(decimal_places=5, max_digits=18)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('datetimeAdjusted', models.DateTimeField(blank=True, null=True)),
                ('adjusted', models.BooleanField(default=False, null=True)),
                ('fullyPaid', models.BooleanField(default=False, null=True)),
                ('runningBalance', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('adjustedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiAdjustedBy', to=settings.AUTH_USER_MODEL)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inwardinventory', to='app.journal')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inwardinventory', to='app.party')),
            ],
        ),
        migrations.CreateModel(
            name='IIItemsMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('totalCost', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('barcode', models.CharField(max_length=50)),
                ('productMark', models.CharField(max_length=50)),
                ('inwardInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiitemsmerch', to='app.inwardinventory')),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiitemsmerch', to='app.merchandiseinventory')),
            ],
        ),
        migrations.CreateModel(
            name='IIAdjustedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('totalCost', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('barcode', models.CharField(max_length=50)),
                ('productMark', models.CharField(max_length=50)),
                ('classfication', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('iiItemsMerch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiadjusteditems', to='app.iiitemsmerch')),
                ('inwardInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiadjusteditems', to='app.inwardinventory')),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iiadjusteditems', to='app.merchandiseinventory')),
            ],
        ),
    ]
