# Generated by Django 3.2.3 on 2021-06-26 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_iiadjusteditems_iiitemsmerch_inwardinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('dateQuoted', models.DateField()),
                ('amountDue', models.DecimalField(decimal_places=5, max_digits=18, null=True)),
                ('amountTotal', models.DecimalField(decimal_places=5, max_digits=18)),
                ('discountPercent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discountPeso', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('taxType', models.CharField(blank=True, max_length=20, null=True)),
                ('taxRate', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('taxPeso', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='app.journal')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='app.party')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
            },
        ),
        migrations.CreateModel(
            name='QQItemsMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('amountTotal', models.DecimalField(decimal_places=5, max_digits=18)),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qqitemsmerch', to='app.merchandiseinventory')),
                ('quotations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qqitemsmerch', to='app.quotations')),
            ],
            options={
                'verbose_name': 'PR Items Merch',
                'verbose_name_plural': 'PR Items Merchs',
            },
        ),
        migrations.CreateModel(
            name='QQCOtherFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255, null=True)),
                ('quotations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qqotherfees', to='app.quotations')),
            ],
        ),
    ]
