# Generated by Django 3.2.3 on 2021-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_qqatc'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qqOtherFees',
            field=models.ManyToManyField(blank=True, to='app.QQCOtherFees'),
        ),
        migrations.AddField(
            model_name='branch',
            name='qqitemsMerch',
            field=models.ManyToManyField(blank=True, to='app.QQItemsMerch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='quotations',
            field=models.ManyToManyField(blank=True, to='app.Quotations'),
        ),
    ]
