# Generated by Django 3.2.3 on 2021-06-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210626_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qqatc',
            field=models.ManyToManyField(blank=True, to='app.QQatc'),
        ),
    ]
