# Generated by Django 3.2.3 on 2021-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_branch_qqatc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='journal',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fullyPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fullyReceived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
