# Generated by Django 3.2.3 on 2021-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210626_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='fullyReceived',
            field=models.BooleanField(default=False),
        ),
    ]
