# Generated by Django 3.2.3 on 2021-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210626_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='qtyReceived',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rred',
        ),
        migrations.AddField(
            model_name='poitemsmerch',
            name='qtyReceived',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
