# Generated by Django 3.2.3 on 2021-06-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20210626_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rritemsmerch',
            name='poitemsmerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsmerch', to='app.poitemsmerch'),
        ),
    ]
