# Generated by Django 3.2.3 on 2021-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_poitemsmerch_qtyreceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitemsmerch',
            name='qtyReceived',
            field=models.IntegerField(default=models.PositiveIntegerField()),
        ),
    ]
