# Generated by Django 3.2.3 on 2021-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210627_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='chequeNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
