# Generated by Django 3.2.3 on 2021-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_salescontract_chequeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='iiAdjustedItems',
            field=models.ManyToManyField(blank=True, to='app.IIAdjustedItems'),
        ),
        migrations.AddField(
            model_name='branch',
            name='iiItemsMerch',
            field=models.ManyToManyField(blank=True, to='app.IIItemsMerch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='inwardInventory',
            field=models.ManyToManyField(blank=True, to='app.InwardInventory'),
        ),
    ]
