# Generated by Django 3.2.3 on 2021-06-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_inwardinventory_amounttotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iiadjusteditems',
            name='productMark',
        ),
    ]
