# Generated by Django 3.2.3 on 2021-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_remove_iiadjusteditems_productmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iiadjusteditems',
            name='remaining',
        ),
        migrations.AddField(
            model_name='iiadjusteditems',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
