# Generated by Django 3.2.3 on 2021-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210628_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='iiadjusteditems',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
