# Generated by Django 3.2.3 on 2021-06-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20210629_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='fullyPaid',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='runningBalance',
        ),
    ]
