# Generated by Django 3.2.3 on 2021-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20210629_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='soitemsmerch',
            options={'verbose_name': 'SO Items Merch', 'verbose_name_plural': 'SO Items Merchs'},
        ),
        migrations.RenameField(
            model_name='qqitemsmerch',
            old_name='amountTotal',
            new_name='totalCost',
        ),
        migrations.RemoveField(
            model_name='qqitemsmerch',
            name='amount',
        ),
        migrations.AddField(
            model_name='qqitemsmerch',
            name='cbm',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qqitemsmerch',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='qqitemsmerch',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
