# Generated by Django 3.2.3 on 2021-06-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20210629_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchprofile', to='app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchDefaultChildAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancesToSupplier', models.ManyToManyField(blank=True, null=True, related_name='branchadvancestosupplier', to='app.AccountChild')),
                ('cashInBank', models.ManyToManyField(blank=True, related_name='branchcashinbank', to='app.AccountChild')),
                ('cashOnHand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchcashonhand', to='app.accountchild')),
                ('ewp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchewp', to='app.accountchild')),
                ('inputVat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchinputvat', to='app.accountchild')),
                ('manuInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchmanuinventory', to='app.accountchild')),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchmerchinventory', to='app.accountchild')),
                ('outputVat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchoutputvat', to='app.accountchild')),
                ('pettyCash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchpettycash', to='app.accountchild')),
                ('ppeEquipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchppeequipment', to='app.accountchild')),
                ('ppePlant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchppeplant', to='app.accountchild')),
                ('ppeProperty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchppeproperty', to='app.accountchild')),
            ],
        ),
    ]
