# Generated by Django 3.2.3 on 2021-07-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20210702_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchprofile',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='branchProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='app.branchprofile'),
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='branchDefaultChildAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchprofile', to='app.branchdefaultchildaccount'),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='fullyPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='fullyPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='fullyPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
