# Generated by Django 3.2.3 on 2021-07-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20210703_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='prepaidExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaidexpense', to='app.accountchild'),
        ),
    ]
