# Generated by Django 3.2.3 on 2021-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_branchdefaultchildaccount_prepaidexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
