# Generated by Django 3.2.3 on 2021-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_paymentvoucher_paymentperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='wep',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='wep',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
    ]
