# Generated by Django 3.2.3 on 2021-07-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_paymentvoucher_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='inwardInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inwardinventory', to='app.inwardinventory'),
        ),
    ]
