# Generated by Django 3.2.3 on 2021-07-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_paymentvoucher_inwardinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('datetimeCreated', models.DateTimeField(null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('datetimeApproved', models.DateTimeField(null=True)),
                ('paymentMethod', models.CharField(max_length=50, null=True)),
                ('paymentPeriod', models.CharField(max_length=50, null=True)),
                ('amountDue', models.DecimalField(decimal_places=5, max_digits=18)),
                ('amountTotal', models.DecimalField(decimal_places=5, max_digits=18)),
                ('wep', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True)),
                ('outputVat', models.DecimalField(decimal_places=5, default=0.0, max_digits=20, null=True)),
                ('amountPaid', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivepayment', to='app.journal')),
                ('salesContract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivepayment', to='app.salescontract')),
            ],
        ),
    ]
