# Generated by Django 3.2.3 on 2021-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_receivepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='receivePayment',
            field=models.ManyToManyField(blank=True, to='app.ReceivePayment'),
        ),
    ]
