# Generated by Django 3.2.3 on 2021-07-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_branch_receivepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivepayment',
            name='approvedBy',
        ),
        migrations.RemoveField(
            model_name='receivepayment',
            name='datetimeApproved',
        ),
        migrations.RemoveField(
            model_name='receivepayment',
            name='wep',
        ),
    ]
