# Generated by Django 3.2.3 on 2021-07-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20210706_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='amountPaid',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='paymentPeriod',
        ),
    ]
