# Generated by Django 3.2.3 on 2021-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20210706_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempscotherfees',
            name='fee',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
