# Generated by Django 3.2.3 on 2021-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_alter_tempscotherfees_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseinventory',
            name='inventoryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
