# Generated by Django 3.2.3 on 2021-07-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_merchandiseinventory_inventorydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='costOfSales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchcostofsales', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchsales', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='prepaidExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchprepaidexpense', to='app.accountchild'),
        ),
    ]
