# Generated by Django 3.2.3 on 2021-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_auto_20210707_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivepayment',
            name='wep',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
