# Generated by Django 3.2.3 on 2021-07-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_receivepayment_wep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='crte',
            field=models.BooleanField(default=False),
        ),
    ]
