# Generated by Django 3.2.3 on 2021-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_party_crte'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivepayment',
            name='chequeNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
