# Generated by Django 3.2.3 on 2021-07-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_receivepayment_chequeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivepayment',
            name='amountDue',
        ),
        migrations.RemoveField(
            model_name='receivepayment',
            name='amountTotal',
        ),
        migrations.RemoveField(
            model_name='receivepayment',
            name='outputVat',
        ),
    ]
