# Generated by Django 3.2.3 on 2021-07-07 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20210707_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='wep',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
    ]
