# Generated by Django 3.2.3 on 2021-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20210707_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
