# Generated by Django 3.2.3 on 2021-07-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_deliveries_amounttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='otherIncome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchotherincome', to='app.accountchild'),
        ),
    ]
