# Generated by Django 3.2.3 on 2021-07-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20210708_0038'),
        ('app', '0096_branchdefaultchildaccount_otherincome'),
    ]

    operations = [
    ]
