# Generated by Django 3.2.3 on 2021-07-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_merge_20210708_0039'),
        ('app', '0097_merge_20210708_0051'),
    ]

    operations = [
    ]
