# Generated by Django 3.2.3 on 2021-07-12 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_merge_20210708_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('totalLost', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('type', models.CharField(max_length=50)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetimeCreated', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('newWarehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyTransfered', models.IntegerField(blank=True, null=True)),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritemsmerch', to='app.merchandiseinventory')),
                ('oldWarehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritemsmerch', to='app.warehouse')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritemsmerch', to='app.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='adjustment_photos')),
                ('adjustments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustmentsphotos', to='app.deliveries')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyAdjusted', models.IntegerField(blank=True, null=True)),
                ('adjustments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditemsmerch', to='app.adjustments')),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditemsmerch', to='app.merchandiseinventory')),
            ],
        ),
    ]
