# Generated by Django 3.2.3 on 2021-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_adjustments_adjustmentsitems_adjustmentsphotos_transfer_transferitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='adjustmentItems',
            field=models.ManyToManyField(blank=True, to='app.AdjustmentsItems'),
        ),
        migrations.AddField(
            model_name='branch',
            name='adjustmentPhotos',
            field=models.ManyToManyField(blank=True, to='app.AdjustmentsPhotos'),
        ),
        migrations.AddField(
            model_name='branch',
            name='adjustments',
            field=models.ManyToManyField(blank=True, to='app.Adjustments'),
        ),
        migrations.AddField(
            model_name='branch',
            name='transfer',
            field=models.ManyToManyField(blank=True, to='app.Transfer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='transferItems',
            field=models.ManyToManyField(blank=True, to='app.TransferItems'),
        ),
    ]
