# Generated by Django 3.2.3 on 2021-07-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_auto_20210712_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentsitems',
            name='adjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditems', to='app.adjustments'),
        ),
        migrations.AlterField(
            model_name='adjustmentsitems',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='oldWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritems', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tritems', to='app.transfer'),
        ),
    ]
