# Generated by Django 3.2.3 on 2021-07-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_auto_20210712_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandiseinventory',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='WarehouseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyT', models.IntegerField()),
                ('qtyR', models.IntegerField()),
                ('qtyA', models.IntegerField()),
                ('merchInventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouseitems', to='app.merchandiseinventory')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouseitems', to='app.warehouse')),
            ],
        ),
    ]
