# Generated by Django 3.2.3 on 2021-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_branch_warehouseitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentsitems',
            name='remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustmentsitems',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='adjustmentsitems',
            name='unitCost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
