# Generated by Django 3.2.3 on 2021-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_auto_20210714_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='voided',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
