# Generated by Django 3.2.3 on 2021-07-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_auto_20210718_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivepayment',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
