# Generated by Django 3.2.3 on 2021-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_receivepayment_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scitemsmerch',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='scitemsmerch',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='scitemsmerch',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
