# Generated by Django 3.2.3 on 2021-07-19 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_auto_20210719_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='datetimeVoided',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='voided',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
