# Generated by Django 3.2.3 on 2021-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_auto_20210719_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchild',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='accountchild',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='accountsubgroup',
            name='code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='accountsubgroup',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
