# Generated by Django 3.2.3 on 2021-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_receivingreport_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='first',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
