# Generated by Django 3.2.3 on 2021-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_paymentvoucher_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardinventory',
            name='first',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
