# Generated by Django 3.2.3 on 2021-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_paymentvoucher_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('purchasingPrice', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Other Inventory',
                'verbose_name_plural': 'Other Inventories',
            },
        ),
    ]
