# Generated by Django 3.2.3 on 2021-07-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_otherinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRItemsOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('otherInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pritemsother', to='app.otherinventory')),
                ('purchaseRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pritemsother', to='app.purchaserequest')),
            ],
            options={
                'verbose_name': 'PR Items Other',
                'verbose_name_plural': 'PR Items Others',
            },
        ),
    ]
