# Generated by Django 3.2.3 on 2021-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_pritemsother'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='otherInventory',
            field=models.ManyToManyField(blank=True, to='app.OtherInventory'),
        ),
        migrations.AddField(
            model_name='branch',
            name='prItemsOther',
            field=models.ManyToManyField(blank=True, to='app.PRItemsOther'),
        ),
    ]
