# Generated by Django 3.2.3 on 2021-07-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_auto_20210729_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinventory',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.accountchild'),
        ),
    ]
