# Generated by Django 3.2.3 on 2021-07-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_inwardinventory_first'),
        ('app', '0120_auto_20210729_1650'),
    ]

    operations = [
    ]
