# Generated by Django 3.2.3 on 2021-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_otherinventory_accountchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='pritemsmerch',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
