# Generated by Django 3.2.3 on 2021-07-31 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_branch_poitemsother'),
    ]

    operations = [
        migrations.CreateModel(
            name='RRItemsOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('purchasingPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('totalPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('delivered', models.BooleanField(default=False, null=True)),
                ('otherInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsother', to='app.otherinventory')),
                ('poitemsother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsother', to='app.poitemsother')),
                ('receivingReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rritemsother', to='app.receivingreport')),
            ],
        ),
    ]
