# Generated by Django 3.2.3 on 2021-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_rritemsother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingreport',
            name='amountPaid',
        ),
        migrations.RemoveField(
            model_name='receivingreport',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='receivingreport',
            name='paymentPeriod',
        ),
    ]
