# Generated by Django 3.2.3 on 2021-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_auto_20210731_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='rrItemsOther',
            field=models.ManyToManyField(blank=True, to='app.RRItemsOther'),
        ),
    ]
