# Generated by Django 3.2.3 on 2021-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_branch_rritemsother'),
    ]

    operations = [
        migrations.AddField(
            model_name='rritemsother',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
