# Generated by Django 3.2.3 on 2021-07-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_merge_20210731_2131'),
        ('app', '0129_rritemsother_type'),
    ]

    operations = [
    ]
