# Generated by Django 3.2.3 on 2021-08-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_purchaseorder_needsrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseinventory',
            name='qtyS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouseitems',
            name='qtyS',
            field=models.IntegerField(default=0),
        ),
    ]
