# Generated by Django 3.2.3 on 2021-08-03 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_auto_20210803_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchild',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountsubgroup',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='totalLost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='atc',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='thicc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='thicc',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='amountTotal',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='pricePerCubic',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='purchasingPrice',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='sellingPrice',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='poatc',
            name='amountWithheld',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amountDue',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='qqatc',
            name='amountWithheld',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='amountDue',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='discountPercent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='amountDue',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rratc',
            name='amountWithheld',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='amountDue',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='amountPaid',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='discountPercent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='amountDue',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='amountTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='scatc',
            name='amountWithheld',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='soatc',
            name='amountWithheld',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='soitemsmerch',
            name='pricePerCubic',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='soitemsmerch',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='soitemsmerch',
            name='vol',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='subTotal',
            field=models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotesitemsmerch',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
