# Generated by Django 3.2.3 on 2021-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_auto_20210803_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iiitemsmerch',
            old_name='amount',
            new_name='pricePerCubic',
        ),
        migrations.RemoveField(
            model_name='iiadjusteditems',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='iiitemsmerch',
            name='productMark',
        ),
        migrations.AddField(
            model_name='iiitemsmerch',
            name='classfication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iiitemsmerch',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iiitemsmerch',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
