# Generated by Django 3.2.3 on 2021-08-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_auto_20210811_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentsitems',
            name='oldWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aditems', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='pricePerCubic',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='thicc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
