# Generated by Django 3.2.3 on 2021-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_auto_20210812_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitemsmerch',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
        migrations.AddField(
            model_name='poitemsother',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
        migrations.AddField(
            model_name='pritemsmerch',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
        migrations.AddField(
            model_name='pritemsother',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
        migrations.AddField(
            model_name='rritemsmerch',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
        migrations.AddField(
            model_name='rritemsother',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'PC'), (1, 'KG'), (2, 'L')], null=True),
        ),
    ]
