# Generated by Django 3.2.3 on 2021-08-21 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_auto_20210819_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeIn', models.DateTimeField(blank=True, null=True)),
                ('dateTimeOut', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ut', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dtr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, choices=[(0, 'SUN'), (1, 'MON'), (2, 'TUE'), (3, 'WED'), (4, 'THU'), (5, 'FRI'), (6, 'SAT')], null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='dayOff',
            field=models.ManyToManyField(blank=True, to='app.DayOff'),
        ),
        migrations.AddField(
            model_name='branch',
            name='dtr',
            field=models.ManyToManyField(blank=True, to='app.DTR'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schedule'),
        ),
    ]
