# Generated by Django 3.2.3 on 2021-08-26 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_auto_20210821_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivepayment',
            name='chequeNo',
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequeNo', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateField(null=True)),
                ('accountChild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='app.accountchild')),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('receivePayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='app.receivepayment')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='cheque',
            field=models.ManyToManyField(blank=True, to='app.Cheques'),
        ),
    ]
