# Generated by Django 3.2.3 on 2021-08-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_auto_20210826_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques',
            name='paymentVoucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='app.paymentvoucher'),
        ),
    ]
