# Generated by Django 3.2.3 on 2021-08-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_cheques_paymentvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheques',
            name='paymentVoucher',
        ),
        migrations.RemoveField(
            model_name='cheques',
            name='receivePayment',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.cheques'),
        ),
        migrations.AddField(
            model_name='receivepayment',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivepayment', to='app.cheques'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='inwardInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.inwardinventory'),
        ),
    ]
