# Generated by Django 3.2.3 on 2021-08-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_auto_20210826_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.salescontract'),
        ),
        migrations.AddField(
            model_name='receivepayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivepayment', to='app.purchaseorder'),
        ),
    ]
