# Generated by Django 3.2.3 on 2021-09-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_auto_20210831_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='datetimeApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='datetimeCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='first',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='paymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receivingReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentvoucher', to='app.salescontract'),
        ),
    ]
