# Generated by Django 3.2.3 on 2021-09-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_auto_20210905_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.party'),
        ),
        migrations.AddField(
            model_name='receivepayment',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.party'),
        ),
        migrations.CreateModel(
            name='CustomRPEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normally', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True)),
                ('accountChild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customrpentries', to='app.accountchild')),
                ('receivePayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customrpentries', to='app.receivepayment')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPVEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normally', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True)),
                ('accountChild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custompventries', to='app.accountchild')),
                ('paymentVoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custompventries', to='app.paymentvoucher')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='customPVEntries',
            field=models.ManyToManyField(blank=True, to='app.CustomPVEntries'),
        ),
        migrations.AddField(
            model_name='branch',
            name='customRPEntries',
            field=models.ManyToManyField(blank=True, to='app.CustomRPEntries'),
        ),
    ]
