# Generated by Django 3.2.3 on 2021-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_ppe_purchaseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ppe',
            field=models.ManyToManyField(blank=True, to='app.PPE'),
        ),
        migrations.AddField(
            model_name='branch',
            name='ppeHistoryOfDepr',
            field=models.ManyToManyField(blank=True, to='app.PPEHistoryOfDepr'),
        ),
        migrations.AddField(
            model_name='branch',
            name='repairAndMaintenance',
            field=models.ManyToManyField(blank=True, to='app.RepairAndMaintenance'),
        ),
    ]
