# Generated by Django 3.2.3 on 2021-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_auto_20210913_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppe',
            name='deprCycle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
