# Generated by Django 3.2.3 on 2021-09-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_ppe_deprcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppe',
            name='startingDeprDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
