# Generated by Django 3.2.3 on 2021-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_ppe_startingdeprdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppe',
            name='deprRate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
