# Generated by Django 3.2.3 on 2021-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_alter_merchandiseinventory_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='qqd',
            field=models.BooleanField(default=False),
        ),
    ]
