# Generated by Django 3.2.3 on 2021-09-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_auto_20210918_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='defaultWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchdefaultwarehouse', to='app.warehouse'),
        ),
    ]
