# Generated by Django 3.2.3 on 2021-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0157_branchdefaultchildaccount_defaultwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='test/')),
            ],
        ),
    ]
