# Generated by Django 3.2.3 on 2021-09-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_auto_20210922_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionreport',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completionreport',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completionreportapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completionreport',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completionreportcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='ppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completionreport', to='app.ppe'),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='spareParts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completionreport', to='app.receivingreport'),
        ),
    ]
