# Generated by Django 3.2.3 on 2021-09-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0161_auto_20210922_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crpo', to='app.completionreport')),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crpo', to='app.purchaseorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='crVendors',
        ),
        migrations.DeleteModel(
            name='CRVendors',
        ),
        migrations.AddField(
            model_name='branch',
            name='crpo',
            field=models.ManyToManyField(blank=True, to='app.CRPO'),
        ),
    ]
