# Generated by Django 3.2.3 on 2021-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_auto_20210924_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='repairAndMaintenance',
        ),
        migrations.AddField(
            model_name='completionreport',
            name='capitalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='completionreport',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='RepairAndMaintenance',
        ),
    ]
