# Generated by Django 3.2.3 on 2021-10-04 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_auto_20210925_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ut', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('nd', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ndot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sun', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sunot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rhot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('normalDay', models.BooleanField(default=True)),
                ('dtr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.dtr')),
            ],
        ),
        migrations.CreateModel(
            name='UTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOut', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('datetimeCreated', models.DateTimeField(blank=True, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utrequestapprovedby', to=settings.AUTH_USER_MODEL)),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utrequestrequestedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.holiday')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='OTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('datetimeCreated', models.DateTimeField(blank=True, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otrequestapprovedby', to=settings.AUTH_USER_MODEL)),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otrequestrequestedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('leaveType', models.CharField(blank=True, max_length=64, null=True)),
                ('datetimeCreated', models.DateTimeField(blank=True, null=True)),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaverequestapprovedby', to=settings.AUTH_USER_MODEL)),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaverequestrequestedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
