# Generated by Django 3.2.3 on 2021-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0167_auto_20211004_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='nd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='ndot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
