# Generated by Django 3.2.3 on 2021-10-08 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_auto_20211006_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='timesheetDayCategory',
        ),
        migrations.AddField(
            model_name='dtr',
            name='bh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='normalDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='rhot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='sh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='shot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='sun',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='sunot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='TimesheetDayCategory',
        ),
        migrations.AddField(
            model_name='dtrdaycategory',
            name='dtr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.dtr'),
        ),
        migrations.AddField(
            model_name='dtrdaycategory',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.holiday'),
        ),
        migrations.AddField(
            model_name='branch',
            name='dtrDayCategory',
            field=models.ManyToManyField(blank=True, to='app.DTRDayCategory'),
        ),
    ]
