# Generated by Django 3.2.3 on 2021-10-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_auto_20211008_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchild',
            name='accountSubGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountchild', to='app.accountsubgroup'),
        ),
        migrations.AlterField(
            model_name='accountchild',
            name='me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountchild', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='accountsubgroup',
            name='accountGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountsubgroup', to='app.accountgroup'),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adjustmentsitems',
            name='adjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditems', to='app.adjustments'),
        ),
        migrations.AlterField(
            model_name='adjustmentsitems',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='adjustmentsitems',
            name='oldWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditems', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='adjustmentsphotos',
            name='adjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustmentsphotos', to='app.deliveries'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='app.branchprofile'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='cashOnHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchcashonhand', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='costOfSales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchcostofsales', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='cwit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchcwit', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='defaultWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchdefaultwarehouse', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='ewp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchewp', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='inputVat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchinputvat', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='manuInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchmanuinventory', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchmerchinventory', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='otherIncome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchotherincome', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='outputVat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchoutputvat', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='pettyCash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchpettycash', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='ppeEquipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchppeequipment', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='ppePlant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchppeplant', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='ppeProperty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchppeproperty', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='prepaidExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchprepaidexpense', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchdefaultrm', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchdefaultchildaccount',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchsales', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='branchprofile',
            name='branchDefaultChildAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchprofile', to='app.branchdefaultchildaccount'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completionreportapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completionreportcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='ppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completionreport', to='app.ppe'),
        ),
        migrations.AlterField(
            model_name='completionreport',
            name='spareParts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completionreport', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='crpo',
            name='cr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crpo', to='app.completionreport'),
        ),
        migrations.AlterField(
            model_name='crpo',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crpo', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='crspareparts',
            name='cr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crspareparts', to='app.completionreport'),
        ),
        migrations.AlterField(
            model_name='crspareparts',
            name='receivingReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crspareparts', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='custompventries',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custompventries', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='custompventries',
            name='paymentVoucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custompventries', to='app.paymentvoucher'),
        ),
        migrations.AlterField(
            model_name='customrpentries',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customrpentries', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='customrpentries',
            name='receivePayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customrpentries', to='app.receivepayment'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app.driver'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app.truck'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverydestinations',
            name='deliveries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverydestinations', to='app.deliveries'),
        ),
        migrations.AlterField(
            model_name='deliveryitemmerch',
            name='deliveryItemsGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryitemsmerch', to='app.deliveryitemsgroup'),
        ),
        migrations.AlterField(
            model_name='deliveryitemmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='deliveryitemsgroup',
            name='deliveries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryitemsgroup', to='app.deliveries'),
        ),
        migrations.AlterField(
            model_name='deliveryphotos',
            name='deliveries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryphotos', to='app.deliveries'),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dtrdaycategory',
            name='dtr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dtr'),
        ),
        migrations.AlterField(
            model_name='dtrdaycategory',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.holiday'),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='iiItemsMerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiadjusteditems', to='app.iiitemsmerch'),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='inwardInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiadjusteditems', to='app.inwardinventory'),
        ),
        migrations.AlterField(
            model_name='iiadjusteditems',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiadjusteditems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='inwardInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiitemsmerch', to='app.inwardinventory'),
        ),
        migrations.AlterField(
            model_name='iiitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='adjustedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiAdjustedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inwardinventory', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inwardinventory', to='app.party'),
        ),
        migrations.AlterField(
            model_name='inwardinventory',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iiVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalentries', to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalentries', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaverequestapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='requestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaverequestrequestedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherinventory',
            name='accountChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accountchild'),
        ),
        migrations.AlterField(
            model_name='otrequest',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otrequestapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otrequest',
            name='requestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrequestrequestedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.cheques'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='inwardInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.inwardinventory'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receivingReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentvoucher', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poatc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poatc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='poatc',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poatc', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='poitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='poitemsmerch',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitemsmerch', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='poitemsother',
            name='otherInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitemsother', to='app.otherinventory'),
        ),
        migrations.AlterField(
            model_name='poitemsother',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poitemsother', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='pritemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pritemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='pritemsmerch',
            name='purchaseRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pritemsmerch', to='app.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='pritemsother',
            name='otherInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pritemsother', to='app.otherinventory'),
        ),
        migrations.AlterField(
            model_name='pritemsother',
            name='purchaseRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pritemsother', to='app.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='app.party'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaseRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='app.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qqatc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqatc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='qqatc',
            name='quotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqatc', to='app.quotations'),
        ),
        migrations.AlterField(
            model_name='qqcotherfees',
            name='quotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqotherfees', to='app.quotations'),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='quotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqitemsmerch', to='app.quotations'),
        ),
        migrations.AlterField(
            model_name='qqitemsmerch',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qqitemsmerch', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='app.party'),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepayment', to='app.cheques'),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepayment', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='salesContract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepayment', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='receivepayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepayment', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivingreport', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivingreport', to='app.party'),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivingreport', to='app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='receivingreport',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rratc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rratc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='rratc',
            name='receivingReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rratc', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='rritemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='rritemsmerch',
            name='poitemsmerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsmerch', to='app.poitemsmerch'),
        ),
        migrations.AlterField(
            model_name='rritemsmerch',
            name='receivingReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsmerch', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='rritemsother',
            name='otherInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsother', to='app.otherinventory'),
        ),
        migrations.AlterField(
            model_name='rritemsother',
            name='poitemsother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsother', to='app.poitemsother'),
        ),
        migrations.AlterField(
            model_name='rritemsother',
            name='receivingReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rritemsother', to='app.receivingreport'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempscApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempscCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salescontract', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salescontract', to='app.party'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='salesOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salescontract', to='app.salesorder'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesinvoice', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='salesContract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesinvoice', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='salesOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesinvoice', to='app.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder', to='app.party'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesorder', to='app.quotations'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='voidedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soVoidedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scatc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='scatc',
            name='salesContract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatc', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='scitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='scitemsmerch',
            name='salesContract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scitemsmerch', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='soatc',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soatc', to='app.atc'),
        ),
        migrations.AlterField(
            model_name='soatc',
            name='salesOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soatc', to='app.salesorder'),
        ),
        migrations.AlterField(
            model_name='soitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='soitemsmerch',
            name='salesOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soitemsmerch', to='app.salesorder'),
        ),
        migrations.AlterField(
            model_name='sootherfees',
            name='salesOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sootherfees', to='app.salesorder'),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempsalescontract', to='app.journal'),
        ),
        migrations.AlterField(
            model_name='tempsalescontract',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempsalescontract', to='app.party'),
        ),
        migrations.AlterField(
            model_name='tempscitemsmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempscitemsmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='tempscitemsmerch',
            name='salesContract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempscitemsmerch', to='app.tempsalescontract'),
        ),
        migrations.AlterField(
            model_name='tempscotherfees',
            name='salesContract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scotherfees', to='app.salescontract'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dtr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dtr'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trApprovedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='newWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tritems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='oldWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tritems', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='transferitems',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tritems', to='app.transfer'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='utrequest',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utrequestapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utrequest',
            name='requestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utrequestrequestedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorquotesitemsmerch',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorquotesitemsmerch', to='app.party'),
        ),
        migrations.AlterField(
            model_name='vendorquotesitemsmerch',
            name='vendorquotesmerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorquotesitemsmerch', to='app.vendorquotesmerch'),
        ),
        migrations.AlterField(
            model_name='vendorquotesmerch',
            name='merchInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorquotesmerch', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='vendorquotesmerch',
            name='purchaseRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorquotesmerch', to='app.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='warehouseitems',
            name='merchInventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseitems', to='app.merchandiseinventory'),
        ),
        migrations.AlterField(
            model_name='warehouseitems',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseitems', to='app.warehouse'),
        ),
    ]
