# Generated by Django 3.2.3 on 2021-10-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0170_auto_20211008_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseinventory',
            name='childAccountCostOfSales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchinventorychildaccountcostofsales', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='merchandiseinventory',
            name='childAccountInventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchinventorychildaccountinventory', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='merchandiseinventory',
            name='childAccountSales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchinventorychildaccountsales', to='app.accountchild'),
        ),
    ]
