# Generated by Django 3.2.3 on 2021-10-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0172_auto_20211008_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='paymentPeriod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
