# Generated by Django 3.2.3 on 2021-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_alter_dtr_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtr',
            old_name='sun',
            new_name='rd',
        ),
        migrations.RenameField(
            model_name='dtr',
            old_name='sunnd',
            new_name='rdnd',
        ),
        migrations.RenameField(
            model_name='dtr',
            old_name='sunndot',
            new_name='rdndot',
        ),
        migrations.RenameField(
            model_name='dtr',
            old_name='sunot',
            new_name='rdot',
        ),
        migrations.AddField(
            model_name='dtr',
            name='rhrd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='rhrdnd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='rhrdndot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='rhrdot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='shrd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='shrdnd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='shrdndot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dtr',
            name='shrdot',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
