# Generated by Django 3.2.3 on 2021-10-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0175_auto_20211013_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
