# Generated by Django 3.2.3 on 2021-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0176_alter_dayoff_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='workDays',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
