# Generated by Django 3.2.3 on 2021-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0177_schedule_workdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ut', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rdot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rdnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rdndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shwot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shwnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shwndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhrd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhrdot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhrdnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rhrdndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shrd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shrdot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shrdnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shrdndot', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='app.Schedule'),
        ),
        migrations.AddField(
            model_name='branch',
            name='ratesGroup',
            field=models.ManyToManyField(blank=True, to='app.RatesGroup'),
        ),
    ]
