# Generated by Django 3.2.3 on 2021-10-15 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0178_auto_20211014_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('dateStart', models.DateField(blank=True, null=True)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('dateGenerated', models.DateField(blank=True, null=True)),
                ('dateApproved', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='timesheet',
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
        migrations.AddField(
            model_name='branch',
            name='payroll',
            field=models.ManyToManyField(blank=True, to='app.Payroll'),
        ),
        migrations.AddField(
            model_name='dtr',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dtr', to='app.payroll'),
        ),
    ]
