# Generated by Django 3.2.3 on 2021-10-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_alter_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bonusOfUser',
            field=models.ManyToManyField(blank=True, to='app.BonusOfUser'),
        ),
        migrations.AddField(
            model_name='branch',
            name='bonusPay',
            field=models.ManyToManyField(blank=True, to='app.BonusPay'),
        ),
        migrations.AddField(
            model_name='branch',
            name='deMinimisOfUser',
            field=models.ManyToManyField(blank=True, to='app.DeMinimisOfUser'),
        ),
        migrations.AddField(
            model_name='branch',
            name='deMinimisPay',
            field=models.ManyToManyField(blank=True, to='app.DeMinimisPay'),
        ),
    ]
