# Generated by Django 3.2.3 on 2021-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0183_auto_20211016_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratesgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
