# Generated by Django 3.2.3 on 2021-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0185_auto_20211017_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='basicPay',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='grossPay',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='netPay',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
