# Generated by Django 3.2.3 on 2021-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0190_auto_20211023_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='grossPay',
            new_name='grossPayAfterBonus',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='netPay',
            new_name='netPayAfterTaxes',
        ),
        migrations.AddField(
            model_name='payroll',
            name='grossPayBeforeBonus',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='netPayBeforeTaxes',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
