# Generated by Django 3.2.3 on 2021-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0191_auto_20211023_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagibigEmployeeContribution',
            new_name='PagibigEmployeeDeduction',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='pagibigEmployeeContribution',
        ),
        migrations.AddField(
            model_name='branch',
            name='pagibigEmployeeDeduction',
            field=models.ManyToManyField(blank=True, to='app.PagibigEmployeeDeduction'),
        ),
    ]
