# Generated by Django 3.2.3 on 2021-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0192_auto_20211023_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phiccontributionrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
