# Generated by Django 3.2.3 on 2021-10-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0195_auto_20211023_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phiccontributionrate',
            name='ee',
        ),
        migrations.RemoveField(
            model_name='phiccontributionrate',
            name='er',
        ),
        migrations.AddField(
            model_name='phiccontributionrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
