# Generated by Django 3.2.3 on 2021-10-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0196_auto_20211023_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagibigemployeededuction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
