# Generated by Django 3.2.3 on 2021-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0197_pagibigemployeededuction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bhTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='ndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='otTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rdTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rdndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rdndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rdotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhrdTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhrdndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhrdndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='rhrdotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shrdTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shrdndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shrdndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shrdotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shwTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shwndTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shwndotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='shwotTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='utTotalHours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
