# Generated by Django 3.2.3 on 2021-10-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0198_auto_20211023_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibigemployeededuction',
            name='pagibigContributionRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagibigemployeededuction', to='app.pagibigcontributionrate'),
        ),
        migrations.AlterField(
            model_name='pagibigemployeededuction',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagibigemployeededuction', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='phicemployeededuction',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phicemployeededuction', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='phicemployeededuction',
            name='phicContributionRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phicemployeededuction', to='app.phiccontributionrate'),
        ),
        migrations.AlterField(
            model_name='sssemployeededuction',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sssemployeededuction', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='sssemployeededuction',
            name='sssContributionRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sssemployeededuction', to='app.ssscontributionrate'),
        ),
    ]
