# Generated by Django 3.2.3 on 2021-10-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0199_auto_20211023_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagibigemployeededuction',
            name='payroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagibigemployeededuction', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='phicemployeededuction',
            name='payroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phicemployeededuction', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='sssemployeededuction',
            name='payroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sssemployeededuction', to='app.payroll'),
        ),
    ]
