# Generated by Django 3.2.3 on 2021-10-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0200_auto_20211023_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrdaycategory',
            name='dtr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrdaycategory', to='app.dtr'),
        ),
        migrations.AlterField(
            model_name='dtrdaycategory',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtrdaycategory', to='app.holiday'),
        ),
    ]
