# Generated by Django 3.2.3 on 2021-10-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0201_auto_20211024_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspay',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuspay', to='app.payroll'),
        ),
        migrations.AlterField(
            model_name='deminimispay',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deminimispay', to='app.payroll'),
        ),
    ]
