# Generated by Django 3.2.3 on 2021-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0202_auto_20211024_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('lowerLimit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('upperLimit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fixedDeduction', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('percentDeduction', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='incomeTaxTable',
            field=models.ManyToManyField(blank=True, to='app.IncomeTaxTable'),
        ),
    ]
