# Generated by Django 3.2.3 on 2021-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0204_auto_20211027_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxtable',
            name='percentDeduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
