# Generated by Django 3.2.3 on 2021-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0205_alter_incometaxtable_percentdeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxtable',
            name='fixedDeduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
