# Generated by Django 3.2.3 on 2021-10-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0206_alter_incometaxtable_fixeddeduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='incomeTaxTable',
        ),
    ]
