# Generated by Django 3.2.3 on 2021-10-27 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0207_remove_branch_incometaxtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('incometaxtable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.incometaxtable')),
                ('payroll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeetaxdeduction', to='app.payroll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
