# Generated by Django 3.2.3 on 2021-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0208_employeetaxdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='holidayPay',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
