# Generated by Django 3.2.3 on 2021-11-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0209_payroll_holidaypay'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrequest',
            name='dtr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dtr'),
        ),
        migrations.AddField(
            model_name='utrequest',
            name='dtr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dtr'),
        ),
    ]
