# Generated by Django 3.2.3 on 2021-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0210_auto_20211101_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeMinimis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
        ),
    ]
