# Generated by Django 3.2.3 on 2021-11-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0211_deminimis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='TaxableDeMinimisPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxabledeminimispay', to='app.payroll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxabledeminimispay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
