# Generated by Django 3.2.3 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0212_auto_20211102_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
