# Generated by Django 3.2.3 on 2021-11-02 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0213_user_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deminimisofuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deminimisofuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
