# Generated by Django 3.2.3 on 2021-11-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0216_alter_otrequest_dtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrollapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolluser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='app.payroll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='payslip',
            field=models.ManyToManyField(blank=True, to='app.Payslip'),
        ),
    ]
