# Generated by Django 3.2.3 on 2021-11-11 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0217_auto_20211106_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sLeave', models.IntegerField(default=0)),
                ('vLeave', models.IntegerField(default=0)),
                ('uLeave', models.IntegerField(default=0)),
                ('silp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userleave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
