# Generated by Django 3.2.3 on 2021-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0220_raise'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='race',
            field=models.ManyToManyField(blank=True, to='app.Raise'),
        ),
    ]
