# Generated by Django 3.2.3 on 2021-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0221_branch_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
