# Generated by Django 3.2.3 on 2021-11-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0222_alter_holiday_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='position',
            field=models.ManyToManyField(blank=True, to='app.Positions'),
        ),
    ]
