# Generated by Django 3.2.3 on 2021-11-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0223_auto_20211114_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
