# Generated by Django 3.2.3 on 2021-11-14 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0224_rename_positions_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raisse', to=settings.AUTH_USER_MODEL),
        ),
    ]
