# Generated by Django 3.2.3 on 2021-11-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0225_alter_raise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='previousPayroll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previouspayroll', to='app.payroll'),
        ),
    ]
