# Generated by Django 3.2.3 on 2021-11-16 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0227_alter_payroll_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(blank=True, null=True)),
                ('startOfAmortization', models.DateField(blank=True, null=True)),
                ('endOfAmortization', models.DateField(blank=True, null=True)),
                ('loanType', models.CharField(blank=True, max_length=256, null=True)),
                ('loanFrom', models.CharField(blank=True, max_length=128, null=True)),
                ('loanAmount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('serviceFee', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('serviceFeeRate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('netProceeds', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('interestAmount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('interestRate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('totalWithInterest', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('amountPaid', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('fullyPaid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loandeduction', to='app.loans')),
                ('payroll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loandeduction', to='app.payroll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
