# Generated by Django 3.2.3 on 2021-11-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0228_loandeduction_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='loanDeduction',
            field=models.ManyToManyField(blank=True, to='app.LoanDeduction'),
        ),
        migrations.AddField(
            model_name='branch',
            name='loans',
            field=models.ManyToManyField(blank=True, to='app.Loans'),
        ),
        migrations.AddField(
            model_name='loans',
            name='year',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
