# Generated by Django 3.2.3 on 2021-11-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0229_auto_20211116_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='monthlyAmortization',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
