# Generated by Django 3.2.3 on 2021-11-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0230_loans_monthlyamortization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandeduction',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loandeduction', to='app.payroll'),
        ),
    ]
