# Generated by Django 3.2.3 on 2021-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0231_alter_loandeduction_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='amountPaid',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
