# Generated by Django 3.2.3 on 2021-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0233_loandeduction_loanfrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
    ]
