# Generated by Django 3.2.3 on 2021-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0235_auto_20211126_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='projectAssignee',
            field=models.ManyToManyField(blank=True, to='app.ProjectAssignee'),
        ),
        migrations.AddField(
            model_name='branch',
            name='projectDepartment',
            field=models.ManyToManyField(blank=True, to='app.ProjectDepartment'),
        ),
        migrations.AddField(
            model_name='branch',
            name='projectPlan',
            field=models.ManyToManyField(blank=True, to='app.ProjectPlan'),
        ),
        migrations.AddField(
            model_name='branch',
            name='projectStage',
            field=models.ManyToManyField(blank=True, to='app.ProjectStage'),
        ),
        migrations.AddField(
            model_name='branch',
            name='projectTask',
            field=models.ManyToManyField(blank=True, to='app.ProjectTask'),
        ),
    ]
