# Generated by Django 3.2.3 on 2021-11-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0236_auto_20211126_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='deminimisBenefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchdeminimisbenefit', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='hdmfPayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchhdmfpayable', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='hdmfShare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchhdmfshare', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='monthPay13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchmonthpay13', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='phicERShare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchphicershare', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='phicPayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchphicpayable', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='salariesExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchsalariesexpense', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='salariesPayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchsalariespayable', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='sssERShare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchsssershare', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='sssPayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchssspayable', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='withholdingTaxPayable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchwithholdingtaxpayable', to='app.accountchild'),
        ),
    ]
