# Generated by Django 3.2.3 on 2021-12-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0237_auto_20211130_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchbonus', to='app.accountchild'),
        ),
    ]
