# Generated by Django 3.2.3 on 2021-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0238_branchdefaultchildaccount_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchrevenue', to='app.accountchild'),
        ),
    ]
