# Generated by Django 3.2.3 on 2021-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0243_alter_bonuspay_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bonus13th',
            field=models.ManyToManyField(blank=True, to='app.Bonus13th'),
        ),
    ]
