# Generated by Django 3.2.3 on 2021-12-18 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0244_branch_bonus13th'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancementThruPettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('datetimeCreated', models.DateTimeField()),
                ('datetimeApproved', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancementthrupettycashApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancementthrupettycashCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancementthrupettycashissuer', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advancementthrupettycashrequestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='advancementThruPettyCash',
            field=models.ManyToManyField(blank=True, to='app.AdvancementThruPettyCash'),
        ),
    ]
