# Generated by Django 3.2.3 on 2021-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0245_auto_20211218_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancementthrupettycash',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='branch',
            name='pettyCashReplenish',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
