# Generated by Django 3.2.3 on 2021-12-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0247_liquidation_liquidationentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancementthrupettycash',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='advancementthrupettycash',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidation',
            name='advancement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidation', to='app.advancementthrupettycash'),
        ),
    ]
