# Generated by Django 3.2.3 on 2022-01-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0251_liquidation_reimbursementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employeeAccounts',
            field=models.ManyToManyField(blank=True, to='app.AccountChild'),
        ),
    ]
