# Generated by Django 3.2.3 on 2022-01-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0252_user_employeeaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='deMinimis',
            field=models.ManyToManyField(blank=True, to='app.DeMinimis'),
        ),
    ]
