# Generated by Django 3.2.3 on 2022-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0254_exportatc_exportitemsmerch_exportotherfees_exports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exports',
            name='taxPeso',
        ),
        migrations.RemoveField(
            model_name='exports',
            name='taxRate',
        ),
        migrations.RemoveField(
            model_name='exports',
            name='taxType',
        ),
        migrations.AddField(
            model_name='branch',
            name='exportItemsMerch',
            field=models.ManyToManyField(blank=True, to='app.ExportItemsMerch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='exportOtherFees',
            field=models.ManyToManyField(blank=True, to='app.ExportOtherFees'),
        ),
        migrations.AddField(
            model_name='branch',
            name='exports',
            field=models.ManyToManyField(blank=True, to='app.Exports'),
        ),
        migrations.AddField(
            model_name='exportitemsmerch',
            name='pallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exports',
            name='forex',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='Exportatc',
        ),
    ]
