# Generated by Django 3.2.3 on 2022-01-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0255_auto_20220120_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exports',
            name='wep',
        ),
    ]
