# Generated by Django 3.2.3 on 2022-01-20 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0256_remove_exports_wep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivePaymentUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('datetimeCreated', models.DateTimeField(null=True)),
                ('paymentDate', models.DateField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('paymentMethod', models.CharField(max_length=50, null=True)),
                ('paymentPeriod', models.CharField(max_length=50, null=True)),
                ('amountPaid', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepaymentUSD', to='app.cheques')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpUSDCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('exports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepaymentUSD', to='app.exports')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivepaymentUSD', to='app.journal')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.party')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='receivepaymentsUSD',
            field=models.ManyToManyField(blank=True, to='app.ReceivePaymentUSD'),
        ),
    ]
