# Generated by Django 3.2.3 on 2022-01-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0257_auto_20220120_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivepaymentusd',
            name='forex',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
