# Generated by Django 3.2.3 on 2022-01-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0258_receivepaymentusd_forex'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('datatimeCreated', models.DateTimeField(blank=True, null=True)),
                ('jobOrderCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('datetimeFinished', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joApprovedBy', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joborder', to='app.journal')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('purchasingPrice', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterials', to='app.joborder')),
                ('merchInventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterials', to='app.merchandiseinventory')),
            ],
        ),
        migrations.CreateModel(
            name='OverheadExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overheadexpenses', to='app.accountchild')),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overheadexpenses', to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('unitCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiallosses', to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('length', models.DecimalField(decimal_places=5, max_digits=20)),
                ('width', models.DecimalField(decimal_places=5, max_digits=20)),
                ('height', models.DecimalField(decimal_places=5, max_digits=20)),
                ('purchasingPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('sellingPrice', models.DecimalField(decimal_places=5, max_digits=20)),
                ('vol', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventoryDate', models.DateField(blank=True, null=True)),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturinginventory', to='app.joborder')),
            ],
            options={
                'verbose_name': 'Merchandise Inventory',
                'verbose_name_plural': 'Merchandise Inventories',
            },
        ),
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('unitCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalproduct', to='app.joborder')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='finalProduct',
            field=models.ManyToManyField(blank=True, to='app.FinalProduct'),
        ),
        migrations.AddField(
            model_name='branch',
            name='jobOrder',
            field=models.ManyToManyField(blank=True, to='app.JobOrder'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manufacturingInventory',
            field=models.ManyToManyField(blank=True, to='app.ManufacturingInventory'),
        ),
        migrations.AddField(
            model_name='branch',
            name='materialLosses',
            field=models.ManyToManyField(blank=True, to='app.MaterialLosses'),
        ),
        migrations.AddField(
            model_name='branch',
            name='overheadExpenses',
            field=models.ManyToManyField(blank=True, to='app.OverheadExpenses'),
        ),
        migrations.AddField(
            model_name='branch',
            name='rawMaterials',
            field=models.ManyToManyField(blank=True, to='app.RawMaterials'),
        ),
    ]
