# Generated by Django 3.2.3 on 2022-01-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0260_rename_datatimecreated_joborder_datetimecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
