# Generated by Django 3.2.3 on 2022-01-30 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0261_alter_merchandiseinventory_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='laborExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchlaborexpense', to='app.accountchild'),
        ),
    ]
