# Generated by Django 3.2.3 on 2022-01-30 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0262_branchdefaultchildaccount_laborexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directlabor', to='app.accountchild')),
                ('jobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directlabor', to='app.joborder')),
            ],
        ),
    ]
