# Generated by Django 3.2.3 on 2022-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0263_directlabor'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='directLabor',
            field=models.ManyToManyField(blank=True, to='app.DirectLabor'),
        ),
    ]
