# Generated by Django 3.2.3 on 2022-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0265_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='app.Notifications'),
        ),
    ]
