# Generated by Django 3.2.3 on 2022-01-31 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0266_branch_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='factorySupplies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchfactorysupplies', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='materialLosses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchmateriallosses', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='workInProgress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchworkinprogress', to='app.accountchild'),
        ),
    ]
