# Generated by Django 3.2.3 on 2022-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0267_auto_20220131_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='exports',
            name='runningBalancePeso',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
