# Generated by Django 3.2.3 on 2022-02-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0268_exports_runningbalancepeso'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='forexGain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchforexgain', to='app.accountchild'),
        ),
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='forexLoss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchforexloss', to='app.accountchild'),
        ),
    ]
