# Generated by Django 3.2.3 on 2022-02-03 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0269_auto_20220203_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directlabor',
            name='cost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='qty',
            field=models.PositiveIntegerField(default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='unitCost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='materiallosses',
            name='qty',
            field=models.PositiveIntegerField(default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='materiallosses',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='materiallosses',
            name='unitCost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='overheadexpenses',
            name='cost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='purchasingPrice',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='qty',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='totalCost',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=20),
        ),
    ]
