# Generated by Django 3.2.3 on 2022-02-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0271_auto_20220206_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trasfer_photos')),
                ('transfer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferphotos', to='app.transfer')),
            ],
        ),
    ]
