# Generated by Django 3.2.3 on 2022-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0272_transferphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='transferPhotos',
            field=models.ManyToManyField(blank=True, to='app.TransferPhotos'),
        ),
    ]
