# Generated by Django 3.2.3 on 2022-02-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0273_branch_transferphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentsphotos',
            name='adjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustmentsphotos', to='app.adjustments'),
        ),
    ]
