# Generated by Django 3.2.3 on 2022-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0274_alter_adjustmentsphotos_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiseinventory',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True),
        ),
    ]
