# Generated by Django 3.2.3 on 2022-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0276_auto_20220305_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authLevel',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
    ]
