# Generated by Django 3.2.3 on 2022-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0277_alter_user_authlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_message', models.TextField()),
                ('err_url', models.URLField()),
                ('err_line', models.TextField()),
                ('err_datetime', models.DateTimeField()),
            ],
        ),
    ]
