# Generated by Django 3.2.3 on 2022-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0280_auto_20220411_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
