# Generated by Django 3.2.3 on 2022-04-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0281_payslip_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdefaultchildaccount',
            name='cashInBankForPayroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchcashinbankforpayroll', to='app.accountchild'),
        ),
    ]
